#!/usr/bin/env python3
"""Build ui-kit/kit.css + ui-kit/shell.html from the painted ui-visual screens.

The kit is the SAME working cascade the painted pages use, consolidated into one
self-contained file so screens can be composed from it:

  kit.css = fonts
          + structural base (event-feed inline <style>, the grey-box skeleton)
          + Event Detail structural additions (event-detail inline <style>, from
            the "Event Detail layout" marker onward; the shared shell above it is
            already carried by the feed base, so it is not duplicated)
          + Vault base tokens + component skin (_theme-vault.css)
          + Vault two-stone layer (_theme.css)

The wireframe screen-tree rail (@media 1440 -> padding-left:250px) is stripped
(no kit markup carries it). The course roadmap sidebar chrome is KEPT: kit.html
docks it as its own component index, and its desktop offset is scoped to
body:has(#rmSidebar) so the sidebar-less shell.html stays full-width. Everything
else the Vault skin already neutralizes (it hides .wf-*, .zone-tag, .side, .tbd
and re-borders the landmarks), so leftover grey-box selectors match no kit markup
and paint nothing. Asset URLs are re-pointed from ui-visual/ to ../ui-visual/assets
so the kit renders the shipped photos until Step 04 swaps in visuals/.

Idempotent. Never edits ui-visual/ or wireframes/. Re-run after any theme edit.
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
UV = ROOT / "ui-visual"
OUT = ROOT / "ui-kit"

def read(p): return (UV / p).read_text(encoding="utf-8")

def inner_style(html):
    m = re.search(r"<style>(.*?)</style>", html, re.S)
    return m.group(1)

def drop_at_rule(css, needle):
    """Remove a top-level @media rule whose header contains `needle`, brace-balanced."""
    i = css.find("@media")
    while i != -1:
        head_end = css.find("{", i)
        header = css[i:head_end]
        if needle in header:
            depth, j = 0, head_end
            while j < len(css):
                if css[j] == "{": depth += 1
                elif css[j] == "}":
                    depth -= 1
                    if depth == 0:
                        return css[:i] + css[j+1:]
                j += 1
        i = css.find("@media", i + 6)
    return css

def drop_section(css, start_marker, end_marker):
    """Remove text from start_marker up to (not including) end_marker."""
    s = css.find(start_marker)
    e = css.find(end_marker, s + 1) if s != -1 else -1
    return css[:s] + css[e:] if (s != -1 and e != -1) else css

def fix_assets(css):
    return re.sub(r"url\((['\"]?)assets/", r"url(\1../ui-visual/assets/", css)

# --- 1. structural base (feed) : strip the wf-nav rail media -----------------
base = inner_style(read("event-feed.html"))
base = drop_at_rule(base, "min-width: 1440px")

# --- 2. Event Detail structural additions (from the marker onward) ----------
det = inner_style(read("event-detail.html"))
mark = det.find("/* ---- Event Detail layout")
det_extra = det[mark:] if mark != -1 else ""
det_extra = drop_at_rule(det_extra, "min-width: 1440px")

# --- 3. Vault base tokens + skin : keep the roadmap sidebar chrome -----------
# The kit page docks that same course sidebar as its own component index, so we
# KEEP the roadmap-sidebar section + the --rm-* tokens (unlike the earlier build,
# which stripped them). We only scope the desktop offset to pages that actually
# carry the sidebar: shell.html has no #rmSidebar, so it stays full-width.
vault = (UV / "_theme-vault.css").read_text(encoding="utf-8")
vault = vault.replace("body{padding-left:220px!important}",
                      "body:has(#rmSidebar){padding-left:220px!important}")
vault = fix_assets(vault)

# --- 4. Vault two-stone layer : drop the @import (we inline vault) -----------
theme = (UV / "_theme.css").read_text(encoding="utf-8")
theme = re.sub(r'@import url\("_theme-vault\.css"\);\s*', "", theme)
theme = fix_assets(theme)

FONTS = ("@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700"
         "&family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap');\n\n")

HEAD = ("/* ui-kit/kit.css - the Vault component kit (flat). GENERATED by _build_kit.py\n"
        "   from the painted ui-visual screens; hand-maintained after. Do not add color\n"
        "   on a screen: compose from these classes. Tokens live in :root below.\n"
        "   Spec: root DESIGN.md. No em dash. */\n\n")

kit_css = (FONTS + HEAD
    + "/* ============ 1. structural base (grey skeleton; Vault repaints it) ============ */\n"
    + base.strip() + "\n\n"
    + "/* ============ 2. Event Detail / overlays / active-bets / category / tabs ============ */\n"
    + det_extra.strip() + "\n\n"
    + "/* ============ 3. Vault base tokens + component skin ============ */\n"
    + vault.strip() + "\n\n"
    + "/* ============ 4. Vault two-stone layout layer (wins by source order) ============ */\n"
    + theme.strip() + "\n")

(OUT / "kit.css").write_text(kit_css, encoding="utf-8")

# --- shared markup pulled from the painted pages ----------------------------
feed = read("event-feed.html")
detail_html = read("event-detail.html")
# detail sprite is the superset (adds chat / share / heart over the feed's 12)
sprite = re.search(r'<svg width="0" height="0"[^>]*>.*?</svg>', detail_html, re.S).group(0)
header = re.search(r'<header class="app-header">.*?</header>', feed, re.S).group(0)
botnav = re.search(r'<nav class="bottom-nav".*?</nav>', feed, re.S).group(0)
signin = re.search(r'<dialog id="signinDialog".*?</dialog>', feed, re.S).group(0)
deposit = re.search(r'<dialog id="depositDialog".*?</dialog>', feed, re.S).group(0)
# render them inline in the showcase (the pages open them via JS)
signin = signin.replace('<dialog ', '<dialog open ', 1)
deposit = deposit.replace('<dialog ', '<dialog open ', 1)

shell = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>UI Kit - Shell</title>
<link rel="stylesheet" href="kit.css">
</head>
<body>
<!-- The reusable app shell: the two-layer header + the mobile bottom nav.
     Color copies in ui-visual/ take their chrome from here. Icons come from the
     sprite below (inline SVG symbols, Solar Bold). -->
{sprite}
<div class="device app-case">
  {header}
  <main class="feed" style="min-height:60vh">
    <div class="feed-inner">
      <div class="cat-layout"><div class="cat-main">
        <p style="color:var(--muted);font-family:'DM Sans',sans-serif;padding:24px">Shell only. Page content composes here.</p>
      </div></div>
    </div>
  </main>
  {botnav}
</div>
</body>
</html>
"""
(OUT / "shell.html").write_text(shell, encoding="utf-8")

# --- kit.html : the showcase -----------------------------------------------
ODDS = ('<div class="oddsbar"><div class="track"><span class="fill" style="width:%s%%"></span></div>'
        '<div class="lbls"><span class="l-yes">Yes %s%%</span><span class="l-no">No %s%%</span></div></div>')
def odds(y): return ODDS % (y, y, 100 - y)

def card(n, q, why, y):
    return f'''<article class="card"><div class="card-body">
  <div class="top"><span class="thumb"></span><div class="top-txt">
    <a class="q" href="#">{q}</a><p class="why">{why}</p></div></div>
  {odds(y)}
  <div class="yesno"><a href="#"><button>Yes</button></a><a href="#"><button>No</button></a></div>
  <div class="meta"><div class="meta-txt"><span class="m-label">Vol</span> <span class="m-val">$48.2k</span> <span class="m-label">Closes</span> <span class="m-val">Oct 31</span></div>
    <button class="bookmark-btn" aria-pressed="false" aria-label="Save into Favorites"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bookmark-b"/></svg></button></div>
</div></article>'''

multi_card = '''<article class="card"><div class="card-body">
  <div class="top"><span class="thumb"></span><div class="top-txt">
    <a class="q" href="#">Who will win the 2028 U.S. presidential election?</a>
    <p class="why">Early primary polling is unusually close across four names.</p></div></div>
  <div class="options">
    <div class="opt-row"><span class="opt-name">JD Vance</span><span class="opt-prob">34%</span>
      <div class="yesno compact"><a href="#"><button>Yes</button></a><a href="#"><button>No</button></a></div></div>
    <div class="opt-row"><span class="opt-name">Gavin Newsom</span><span class="opt-prob">28%</span>
      <div class="yesno compact"><a href="#"><button>Yes</button></a><a href="#"><button>No</button></a></div></div>
  </div>
  <div class="meta"><div class="meta-txt"><span class="m-label">Vol</span> <span class="m-val">$210k</span> <span class="m-label">Closes</span> <span class="m-val">Nov 2028</span></div>
    <button class="bookmark-btn" aria-pressed="true" aria-label="Saved"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bookmark-b"/></svg></button></div>
</div></article>'''

def SW(hexv, name, tok):
    return (f'<div class="kit-sw"><div class="kit-swatch" style="background:{hexv}">'
            f'<span class="kit-hex">{hexv}</span></div>'
            f'<div class="kit-sw-meta"><b>{name}</b><span>{tok}</span></div></div>')

def TYPE_ROW(role, family, cls, text):
    return (f'<div class="kit-type-row"><div class="kit-role"><b>{role}</b>{family}</div>'
            f'<p class="{cls}">{text}</p></div>')

SHOWCASE_STYLE = '''
  .kit-wrap{max-width:1120px;margin:0 auto;padding:0 20px}
  .kit-hero{padding:44px 0 4px}
  .kit-hero h1{font-family:'Space Grotesk',sans-serif;color:var(--ink);font-size:clamp(30px,5vw,44px);font-weight:700;letter-spacing:-.03em;margin:0;text-wrap:balance}
  .kit-hero p{color:var(--muted);font-family:'DM Sans',sans-serif;margin:10px 0 0;max-width:62ch;line-height:1.55}
  .kit-hero code{font-family:'IBM Plex Mono',monospace;font-size:.9em;color:var(--accent-text)}
  .kit-hero .kit-badge{display:inline-block;font-family:'IBM Plex Mono',monospace;font-size:11px;color:var(--accent-text);border:1px solid var(--brass-line);border-radius:99px;padding:3px 10px;margin-top:16px}
  .kit-jump{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}
  .kit-jump a{font-family:'IBM Plex Mono',monospace;font-size:11px;color:var(--muted);border:1px solid var(--border);border-radius:99px;padding:5px 12px;text-decoration:none;transition:color .15s,border-color .15s}
  .kit-jump a:hover{color:var(--accent-text);border-color:var(--brass-line)}
  .kit-sec{margin-top:44px;border-top:1px solid var(--border);padding-top:24px;scroll-margin-top:20px}
  .kit-sec > h2{font-family:'Space Grotesk',sans-serif;color:var(--accent-text);font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;margin:0 0 4px;display:flex;align-items:center;gap:10px}
  .kit-sec > h2::before{content:attr(data-n);font-family:'IBM Plex Mono',monospace;font-size:10px;color:var(--muted);border:1px solid var(--border);border-radius:5px;padding:1px 6px;letter-spacing:0}
  .kit-sec > .kit-note{color:var(--muted);font-family:'DM Sans',sans-serif;font-size:12.5px;margin:0 0 18px;max-width:72ch;line-height:1.5}
  .kit-subh{color:var(--muted);font-family:'DM Sans',sans-serif;font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;margin:24px 0 10px}
  .kit-row{display:flex;flex-wrap:wrap;gap:14px;align-items:center}
  .kit-row.a-start{align-items:flex-start}
  .kit-sws{display:grid;grid-template-columns:repeat(auto-fill,minmax(132px,1fr));gap:14px}
  .kit-sw{display:flex;flex-direction:column;gap:7px}
  .kit-swatch{position:relative;height:60px;border-radius:8px;border:1px solid rgba(255,255,255,.09);overflow:hidden;display:flex;align-items:flex-end;box-shadow:inset 0 1px 0 rgba(255,255,255,.05)}
  .kit-hex{font-family:'IBM Plex Mono',monospace;font-size:10px;color:#fff;background:rgba(0,0,0,.42);padding:2px 6px;border-radius:5px;margin:6px}
  .kit-sw-meta{display:flex;flex-direction:column;gap:2px}
  .kit-sw-meta b{font-family:'DM Sans',sans-serif;font-size:11.5px;font-weight:600;color:var(--ink)}
  .kit-sw-meta span{font-family:'IBM Plex Mono',monospace;font-size:10px;color:var(--muted)}
  .kit-type{display:grid;gap:0}
  .kit-type-row{display:grid;grid-template-columns:130px 1fr;gap:24px;align-items:baseline;padding:16px 0;border-top:1px solid var(--border)}
  .kit-type-row:first-child{border-top:0;padding-top:2px}
  .kit-role{font-family:'IBM Plex Mono',monospace;font-size:10.5px;color:var(--muted);letter-spacing:.02em;line-height:1.5}
  .kit-role b{display:block;color:var(--accent-text);font-weight:600;text-transform:uppercase;letter-spacing:.06em;margin-bottom:2px}
  .kit-type-row > p{margin:0}
  .t-display{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:clamp(28px,4vw,38px);letter-spacing:-.03em;color:var(--ink);line-height:1.04}
  .t-headline{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:22px;letter-spacing:-.01em;color:var(--ink)}
  .t-title{font-family:'Space Grotesk',sans-serif;font-weight:600;font-size:13px;letter-spacing:-.02em;color:var(--ink)}
  .t-body{font-family:'DM Sans',sans-serif;font-size:13.5px;color:var(--muted);max-width:65ch;line-height:1.5}
  .t-label{font-family:'DM Sans',sans-serif;font-weight:700;font-size:11.5px;letter-spacing:.06em;text-transform:uppercase;color:var(--accent-text)}
  .t-mono{font-family:'IBM Plex Mono',monospace;font-size:13px;color:var(--ink)}
  .kit-box{background:var(--surface);border:1px solid var(--border);border-radius:9px;padding:16px}
  .kit-plate{margin:0}
  dialog.app-dialog[open]{position:static;margin:0;width:100%}
  .kit-dlgs{display:flex;flex-wrap:wrap;gap:20px;align-items:flex-start}
  .kit-dlgs > *{flex:0 1 380px}
  /* showcase-only comfort: the opened dialog is framed with more air than the
     mobile bottom-sheet ships with; the shipped ui-visual sheet is untouched */
  .kit-dlgs .sheet-head{padding:13px 16px}
  .kit-dlgs .sheet-body{padding:16px;gap:14px}
  .kit-dlgs .quick{margin-top:12px}
  main.feed{background:transparent}
  /* chrome specimens: each shell piece framed on its own, not stacked as a page.
     The bottom nav is mobile-only in the app; force it visible here so desktop
     viewers can still see the specimen, and drop sticky so pieces sit in-frame. */
  .kit-chrome-demo{border:1px solid var(--border);border-radius:12px;overflow:hidden;margin-bottom:8px;min-height:0;display:block}
  .kit-chrome-demo .app-header,.kit-chrome-demo .bottom-nav,.kit-chrome-demo .app-footer{position:static}
  .kit-chrome-demo .bottom-nav{display:block}
  @media (max-width:560px){
    .kit-type-row{grid-template-columns:1fr;gap:6px}
  }
'''

GALLERY = f'''
<div class="kit-wrap">
  <header class="kit-hero">
    <h1>Predict Market UI Kit</h1>
    <p>The Vault component kit. Every screen composes from these classes; the look lives in <code>kit.css</code>, the language in <code>DESIGN.md</code>. Seeded from the painted Event Feed and Event Detail families; the account, resolution and system families join it as they are built (Step 05).</p>
    <span class="kit-badge">flat tokens - graphite + matte brass</span>
    <nav class="kit-jump" aria-label="Sections">
      <a href="#f-color">Color</a><a href="#f-type">Type</a><a href="#buttons">Buttons</a><a href="#chips">Chips</a><a href="#cards">Cards</a><a href="#states">States</a><a href="#dialogs">Dialogs</a><a href="#detail">Event Detail</a><a href="#chrome">Chrome</a>
    </nav>
  </header>

  <section class="kit-sec" id="f-color">
    <h2 data-n="01">Foundations - color</h2>
    <p class="kit-note">One matte-brass accent on graphite. Green and red are reserved for the YES / NO outcome only.</p>
    <div class="kit-sws">
      {SW('#c7a24e','Matte Brass','--brass')}{SW('#e6c877','Brass Bright','--brass-2')}{SW('#d7ac53','Brass Text','--accent-text')}
      {SW('#0f1013','Page','--page')}{SW('#141619','Graphite','--canvas')}{SW('#121417','Content Plate','plate')}
      {SW('#14161a','Card Face','card')}{SW('#1c1f24','Surface','--surface')}{SW('#2b2f38','Border','--border')}
      {SW('#ede7da','Ink','--ink')}{SW('#a49d8f','Muted','--muted')}
      {SW('#4fa96b','Outcome Green','--yes')}{SW('#c85a50','Outcome Red','--no')}
    </div>
  </section>

  <section class="kit-sec" id="f-type">
    <h2 data-n="02">Foundations - type</h2>
    <p class="kit-note">Three families on a contrast axis: Space Grotesk display, DM Sans body, IBM Plex Mono numbers.</p>
    <div class="kit-type">
      {TYPE_ROW('Display','Space Grotesk 700','t-display','Not just news. Your stake.')}
      {TYPE_ROW('Headline','Space Grotesk 700','t-headline','Will the U.S. government shut down before Nov 1?')}
      {TYPE_ROW('Title','Space Grotesk 600 - 13px','t-title','Bitcoin above $150,000 this year')}
      {TYPE_ROW('Body','DM Sans 400','t-body','Funding lapses at midnight Friday unless the Senate passes a stopgap. The odds move as new votes are scheduled.')}
      {TYPE_ROW('Label','DM Sans 700 - caps','t-label','Politics - resolves on-chain')}
      {TYPE_ROW('Mono','IBM Plex Mono 500','t-mono','64% - Vol $48.2k - Closes Oct 31')}
    </div>
  </section>

  <section class="kit-sec" id="buttons">
    <h2 data-n="03">Buttons</h2>
    <div class="kit-row">
      <button class="state-btn primary">Confirm bet</button>
      <div class="yesno" style="width:220px"><a href="#"><button>Yes</button></a><a href="#"><button>No</button></a></div>
      <button class="icon-btn" aria-label="Notifications"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bell-b"/></svg></button>
      <button class="load-more">Load more events</button>
    </div>
  </section>

  <section class="kit-sec" id="chips">
    <h2 data-n="04">Chips and filters</h2>
    <div class="feed"><div class="feed-inner" style="padding:0">
      <nav class="cat-nav" aria-label="Categories">
        <ul>
          <li aria-current="page"><a href="#"><button type="button"><svg class="cat-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-cat-fire"/></svg>Trending</button></a></li>
          <li><a href="#"><button type="button"><svg class="cat-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-cat-politics"/></svg>Politics</button></a></li>
          <li><a href="#"><button type="button"><svg class="cat-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-cat-crypto"/></svg>Crypto</button></a></li>
          <li><a href="#"><button type="button"><svg class="cat-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-cat-culture"/></svg>Culture</button></a></li>
          <li><a href="#"><button type="button"><svg class="cat-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-cat-general"/></svg>General</button></a></li>
        </ul>
      </nav>
    </div></div>
    <div class="kit-row" style="margin-top:14px">
      <details class="filter-menu"><summary>Sort: Trending</summary><div class="filter-panel"><ul>
        <li><label><input type="radio" name="s" checked> Trending</label></li>
        <li><label><input type="radio" name="s"> Newest</label></li>
        <li><label><input type="radio" name="s"> Closing soon</label></li></ul></div></details>
      <span class="toggle" role="switch" aria-checked="true">Reverse order</span>
    </div>
  </section>

  <section class="kit-sec" id="cards">
    <h2 data-n="05">Event cards - signature</h2>
    <p class="kit-note">Binary = treatment B (thin odds bar + tinted YES / NO). Multi = treatment D (option rows). On the two-stone content plate.</p>
    <main class="feed"><div class="feed-inner"><div class="cat-layout"><div class="cat-main">
      <div class="grid">
        {card(1,'Will the U.S. government shut down before Nov 1?','Funding lapses at midnight Friday unless the Senate passes a stopgap.',64)}
        {card(2,'Will Bitcoin close above $150,000 this year?','BTC is up 12% this week as spot-ETF inflows hit a record.',58)}
        {multi_card}
      </div>
    </div></div></div></main>
  </section>

  <section class="kit-sec" id="states">
    <h2 data-n="06">States</h2>
    <main class="feed"><div class="feed-inner"><div class="cat-layout"><div class="cat-main">
      <div class="state-block">
        <svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bookmark-b"/></svg>
        <h2 class="state-title">No events match these filters</h2>
        <p class="state-msg">Clear the filters to see everything, or get a note when a new event opens in this category.</p>
        <div class="state-actions"><button class="state-btn primary">Clear filters</button><button class="state-btn">Notify me of new events</button></div>
      </div>
    </div></div></div></main>
    <div class="kit-subh">Error</div>
    <main class="feed"><div class="feed-inner"><div class="cat-layout"><div class="cat-main">
      <div class="state-block">
        <svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l9 16H3z"/><path d="M12 10v4M12 17v.5"/></svg>
        <h2 class="state-title">We could not load events</h2>
        <p class="state-msg">The feed did not respond. Check your connection and try again.</p>
        <div class="state-actions"><button class="state-btn primary">Try again</button></div>
      </div>
    </div></div></div></main>
    <div class="kit-subh">Loading and push</div>
    <main class="feed"><div class="feed-inner"><div class="cat-layout"><div class="cat-main">
      <div class="push-banner"><span class="push-msg"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bell-b"/></svg> Turn on notifications to hear when your events resolve.</span>
        <span class="push-actions"><button class="state-btn primary">Enable</button><button class="state-btn">Not now</button></span></div>
      <div class="grid" style="margin-top:14px">
        <article class="card skeleton"><div class="card-body"><div class="top"><span class="sk-thumb"></span><div class="sk-head"><div class="sk-line w80"></div><div class="sk-line w60"></div></div></div><div class="sk-line w40"></div><div class="sk-row"><span class="sk-btn"></span><span class="sk-btn"></span></div></div></article>
        <article class="card skeleton"><div class="card-body"><div class="top"><span class="sk-thumb"></span><div class="sk-head"><div class="sk-line w80"></div><div class="sk-line w60"></div></div></div><div class="sk-line w40"></div><div class="sk-row"><span class="sk-btn"></span><span class="sk-btn"></span></div></div></article>
      </div>
    </div></div></div></main>
  </section>

  <section class="kit-sec" id="dialogs">
    <h2 data-n="07">Shared dialogs</h2>
    <p class="kit-note">Native <code>&lt;dialog&gt;</code> on the content-plate stone. Sign In (the gate) and Add funds; both emitted once in the shell. Shown inline here.</p>
    <div class="kit-dlgs">
      {signin}
      {deposit}
    </div>
  </section>

  <section class="kit-sec" id="detail">
    <h2 data-n="08">Event Detail</h2>
    <p class="kit-note">Two floating plates: scrolling content + a sticky bet panel. Compact here; the full family lives in ui-visual.</p>
    <main class="feed"><div class="feed-inner"><div class="ed-layout">
      <div class="ed-main"><div class="card"><div class="card-body">
        <div class="ed-head">
          <span class="ed-thumb"></span>
          <div>
            <span class="ed-cat">Politics</span>
            <h1 class="ed-q">Will the U.S. government shut down before Nov 1?</h1>
            <p class="ed-prob-big">Chance <span class="prob">64%</span> yes <span class="prob">36%</span> no</p>
            <div class="ed-oddsbar"><span class="track"><span class="fill" style="width:64%"></span></span></div>
          </div>
          <div class="ed-actions">
            <button aria-label="Comments"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-chat-b"/></svg></button>
            <button aria-label="Share"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-share-b"/></svg></button>
            <button data-fav aria-pressed="false" aria-label="Save into Favorites"><svg class="ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-bookmark-b"/></svg></button>
          </div>
        </div>
        <div class="ed-section"><h3>Resolution</h3><p class="resolution">Resolves <strong>Yes</strong> if a federal funding gap begins before Nov 1, per the official Congressional record.</p></div>
        <div class="ed-section"><h3>Why this price</h3>
          <div class="args"><div class="arg-col"><h4>For Yes</h4><ul><li>No stopgap scheduled before the deadline.</li><li>Both chambers are out until Thursday.</li></ul></div>
          <div class="arg-col"><h4>For No</h4><ul><li>Leadership signaled a short-term deal.</li><li>Markets are pricing a last-minute vote.</li></ul></div></div>
        </div>
      </div></div></div>
      <aside class="bet-panel"><div class="bp-inner">
        <div class="bp-head">Your bet</div>
        <div class="yesno"><a href="#"><button>Yes</button></a><a href="#"><button>No</button></a></div>
        <label class="field-label" style="margin-top:12px;display:block">Amount</label>
        <div class="amount-row"><span class="cur">$</span><input class="amount-input" value="5" aria-label="Amount"></div>
        <p class="bp-hint">If Yes wins you get $7.80. Fee $0.20, only on a win.</p>
        <button class="state-btn primary" style="width:100%">Confirm bet</button>
      </div></aside>
    </div></div></main>
    <div class="kit-subh">Comment</div>
    <main class="feed"><div class="feed-inner">
      <div class="ed-main"><div class="card"><div class="card-body">
        <div class="ed-section">
          <div class="cmt-list"><div class="cmt"><span class="cmt-av"></span><div class="cmt-body">
            <div class="cmt-meta"><span class="cmt-user">mia_k</span> <span class="cmt-badge">Holds 320 Yes</span> <span>2h</span></div>
            <p class="cmt-text">The stopgap vote keeps slipping. I think this closes higher than 64.</p>
            <div class="cmt-actions"><button>Like 12</button><button>Reply</button></div>
          </div></div></div>
        </div>
      </div></div>
    </div></main>
    <div class="kit-subh">Related events</div>
    <main class="feed"><div class="feed-inner">
      <section class="related-events" aria-label="Related events">
        <h2>Related events</h2>
        <ul class="related-list">
          <li><a href="#"><span class="rel-thumb" style="background-image:url(../ui-visual/assets/event-politics.jpg)"></span><span class="rel-q">Will the debt ceiling be raised before Dec 15?</span><span class="rel-odds">Yes 72%</span></a></li>
          <li><a href="#"><span class="rel-thumb" style="background-image:url(../ui-visual/assets/event-crypto.jpg)"></span><span class="rel-q">Will a continuing resolution pass this week?</span><span class="rel-odds">Yes 41%</span></a></li>
        </ul>
        <a href="#" class="related-more">Browse more events</a>
      </section>
    </div></main>
  </section>

  <section class="kit-sec" id="chrome">
    <h2 data-n="09">Chrome</h2>
    <p class="kit-note">The reusable shell, one piece at a time. On a real screen the header sticks to the top and the bottom nav to the bottom, so they are shown as separate specimens here (not stacked). The header is lean on desktop and compact on mobile; the bottom nav is the mobile-only 4-slot bar. See <code>shell.html</code>.</p>
    <div class="kit-subh">Sticky app header</div>
    <div class="device app-case kit-chrome-demo">{header}</div>
    <div class="kit-subh">Mobile bottom nav</div>
    <div class="device app-case kit-chrome-demo">{botnav}</div>
    <div class="kit-subh">Footer trust strip</div>
    <div class="device app-case kit-chrome-demo">
      <footer class="app-footer"><div class="footer-inner">
        <div class="footer-trust"><h3 class="trust-head">Built on trust</h3><div class="trust-items">
          <div class="trust-item"><svg class="tr-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-shield-b"/></svg><div class="tr-txt"><b>USDC held 1:1</b><i>We never lend deposited funds.</i></div></div>
          <div class="trust-item"><svg class="tr-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-verified-b"/></svg><div class="tr-txt"><b>Public sources</b><i>Every event cites its resolution source.</i></div></div>
          <div class="trust-item"><svg class="tr-ic" viewBox="0 0 24 24" aria-hidden="true"><use href="#i-seo-chart"/></svg><div class="tr-txt"><b>1,240 events resolved</b><i>On-chain, and visible to anyone.</i></div></div>
        </div></div>
        <div class="footer-legal"><a class="footer-logo">Predict Market</a><p class="footer-tagline">Not just news. Your stake.</p></div>
      </div></footer>
    </div>
  </section>
</div>
'''

# the same course sidebar the ui-visual screens carry, docked as the kit's index
KIT_SIDEBAR = '''<button type="button" class="rm-toggle" id="rmToggle" aria-label="Open roadmap"><span></span><span></span><span></span></button>
<div class="rm-overlay" id="rmOverlay"></div>
<aside class="sidebar" id="rmSidebar">
  <a href="../research/research.html" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> Course roadmap</a>
  <div class="sidebar-brand"><div class="sidebar-project-name">UI Kit - components</div></div>
  <nav class="sidebar-nav">
    <a href="../ui-visual/event-feed.html" class="sidebar-page-link">UI + Visual - screens</a>
    <a class="sidebar-page-link active">UI Kit</a>
    <div class="sidebar-sub">
      <a href="#f-color" class="sidebar-sub-link">Color</a>
      <a href="#f-type" class="sidebar-sub-link">Type</a>
      <a href="#buttons" class="sidebar-sub-link">Buttons</a>
      <a href="#chips" class="sidebar-sub-link">Chips and filters</a>
      <a href="#cards" class="sidebar-sub-link">Event cards</a>
      <a href="#states" class="sidebar-sub-link">States</a>
      <a href="#dialogs" class="sidebar-sub-link">Shared dialogs</a>
      <a href="#detail" class="sidebar-sub-link">Event Detail</a>
      <a href="#chrome" class="sidebar-sub-link">Chrome</a>
    </div>
  </nav>
</aside>'''

KIT_JS = '''<script>
(function(){var sb=document.getElementById('rmSidebar'),ov=document.getElementById('rmOverlay'),tg=document.getElementById('rmToggle');if(!sb||!ov||!tg)return;var open=function(){sb.classList.add('open');ov.classList.add('open');},close=function(){sb.classList.remove('open');ov.classList.remove('open');};tg.addEventListener('click',open);ov.addEventListener('click',close);sb.querySelectorAll('.sidebar-sub-link').forEach(function(a){a.addEventListener('click',close);});})();
</script>'''

kit_html = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Predict Market - UI Kit</title>
<link rel="stylesheet" href="kit.css">
<style>{SHOWCASE_STYLE}</style>
</head>
<body class="app-case">
{sprite}
{KIT_SIDEBAR}
{GALLERY}
{KIT_JS}
</body>
</html>
'''
(OUT / "kit.html").write_text(kit_html, encoding="utf-8")

# --- report -----------------------------------------------------------------
print("kit.css     :", len(kit_css.splitlines()), "lines")
print("shell.html  :", len(shell.splitlines()), "lines")
print("kit.html    :", len(kit_html.splitlines()), "lines")
print("wf-rail padding-left:250px left:", kit_css.count("padding-left:250px"), "(want 0)")
print("roadmap sidebar docked (:has) :", kit_css.count("body:has(#rmSidebar)"), "(want 1)")
print("theme @import left            :", theme.count('@import'), "(want 0)")
print("assets re-pointed             :", kit_css.count("../ui-visual/assets/"),
      "; raw url(assets left:", len(re.findall(r"url\((['\"]?)assets/", kit_css)))
print("em-dash in kit.css/kit.html   :", kit_css.count(chr(8212)) + kit_html.count(chr(8212)))
