/* ui-kit/_nav.js - the ONE registry of stand pages.

   It renders two things from the same list: the cards on overview.html and the
   kit-only side panel on every stand page. A component without a line here does
   not exist as far as the system is concerned. Own namespace (window.KIT_NAV) so
   it never collides with the course roadmap renderer in the repo root.
   Generated by _gen_component_pages.py. No em dash. */
window.KIT_DOORS = [{"label": "Colour", "file": "tokens.html#colour", "blurb": "Every graphite step and every brass, and the roles that read them."}, {"label": "Material", "file": "tokens.html#material", "blurb": "The two-stone plates, the grain, the bevels and the grooves."}, {"label": "Geometry", "file": "tokens.html#geometry", "blurb": "Spacing, radius, control sizes, the container and the gutter."}, {"label": "Type", "file": "tokens.html#type", "blurb": "Three families, the size ramp, weight and leading."}, {"label": "Motion", "file": "tokens.html#motion", "blurb": "Durations and easings, shown moving."}];
window.KIT_DOCS = [{"name": "doc-architecture", "file": "architecture.html", "label": "Architecture", "blurb": "How the system is put together, what each level may hold, and where a change goes."}, {"name": "doc-atoms", "file": "atoms.html", "label": "The atom map", "blurb": "What the atoms ARE, decided from the 5281 controls the product wears rather than from the files, and the distance from here to there."}, {"name": "doc-history", "file": "history.html", "label": "What each pass settled", "blurb": "The long form of ten audit passes: what was measured, and which check could see it."}, {"name": "doc-tokens-audit", "file": "tokens-audit.html", "label": "Tokens audit", "blurb": "The reading the system was built from: every value the painted product had, and what it meant."}, {"name": "doc-inventory", "file": "inventory.html", "label": "Inventory", "blurb": "Every component, its css file, its page and the screens it stands on."}, {"name": "doc-coverage", "file": "coverage.html", "label": "Coverage", "blurb": "Every class, and how many painted screens carry it. A zero is not a verdict."}, {"name": "doc-backlog", "file": "backlog.html", "label": "System backlog", "blurb": "What the system is missing, found by assembling a screen out of it and adding nothing."}, {"name": "doc-defects", "file": "defects.html", "label": "The defect table", "blurb": "Every class of defect this stage can have, which gate proves it, and what is left to look for by hand."}];
window.KIT_NAV = [
  {group: "Foundations", name: "tokens", file: "tokens.html", label: "Tokens", path: "components/tokens.css"},
  {group: "Foundations", name: "icons", file: "icons.html", label: "Icons", path: "ui-kit/icons.html"},
  {group: "Foundations", name: "base", file: "base.html", label: "Base and page frame", path: "components/base.css"},
  {group: "Foundations", name: "course-chrome", file: "course-chrome.html", label: "Course chrome", path: "components/course-chrome.css"},
  {group: "Atoms", name: "loadmore", file: "loadmore.html", label: "Load more", path: "components/loadmore.css"},
  {group: "Atoms", name: "oddsbar", file: "oddsbar.html", label: "Odds bar", path: "components/oddsbar.css"},
  {group: "Atoms", name: "button", file: "button.html", label: "Buttons", path: "components/button.css"},
  {group: "Atoms", name: "iconbtn", file: "iconbtn.html", label: "iconbtn", path: "components/iconbtn.css"},
  {group: "Atoms", name: "input", file: "input.html", label: "Fields and amounts", path: "components/input.css"},
  {group: "Atoms", name: "toggle", file: "toggle.html", label: "toggle", path: "components/toggle.css"},
  {group: "Atoms", name: "chip", file: "chip.html", label: "chip", path: "components/chip.css"},
  {group: "Molecules", name: "skeleton", file: "skeleton.html", label: "Skeletons", path: "components/skeleton.css"},
  {group: "Molecules", name: "toc", file: "toc.html", label: "toc", path: "components/toc.css"},
  {group: "Molecules", name: "quick", file: "quick.html", label: "quick", path: "components/quick.css"},
  {group: "Molecules", name: "seo-plate", file: "seo-plate.html", label: "SEO plate", path: "components/seo-plate.css"},
  {group: "Molecules", name: "trustbar", file: "trustbar.html", label: "Trust bar and cards", path: "components/trustbar.css"},
  {group: "Molecules", name: "market", file: "market.html", label: "AMM market panel", path: "components/market.css"},
  {group: "Molecules", name: "related", file: "related.html", label: "Related events", path: "components/related.css"},
  {group: "Molecules", name: "yesno", file: "yesno.html", label: "YES / NO buttons", path: "components/yesno.css"},
  {group: "Molecules", name: "toast", file: "toast.html", label: "Toasts", path: "components/toast.css"},
  {group: "Molecules", name: "comments", file: "comments.html", label: "Comments", path: "components/comments.css"},
  {group: "Molecules", name: "filters", file: "filters.html", label: "Sort and filters", path: "components/filters.css"},
  {group: "Molecules", name: "account", file: "account.html", label: "Account bars", path: "components/account.css"},
  {group: "Molecules", name: "cookie-consent", file: "cookie-consent.html", label: "Cookie consent", path: "components/cookie-consent.css"},
  {group: "Organisms", name: "bottomnav", file: "bottomnav.html", label: "Bottom nav", path: "components/bottomnav.css"},
  {group: "Organisms", name: "hero", file: "hero.html", label: "Featured hero", path: "components/hero.css"},
  {group: "Organisms", name: "catnav", file: "catnav.html", label: "Category nav", path: "components/catnav.css"},
  {group: "Organisms", name: "position", file: "position.html", label: "Position rows", path: "components/position.css"},
  {group: "Organisms", name: "notice", file: "notice.html", label: "Notices and banners", path: "components/notice.css"},
  {group: "Organisms", name: "header", file: "header.html", label: "App header", path: "components/header.css"},
  {group: "Organisms", name: "options", file: "options.html", label: "Outcome rows", path: "components/options.css"},
  {group: "Organisms", name: "state-block", file: "state-block.html", label: "State block", path: "components/state-block.css"},
  {group: "Organisms", name: "footer", file: "footer.html", label: "Footer", path: "components/footer.css"},
  {group: "Organisms", name: "card", file: "card.html", label: "Event card", path: "components/card.css"},
  {group: "Organisms", name: "dialog", file: "dialog.html", label: "Shared dialog", path: "components/dialog.css"},
  {group: "Organisms", name: "bets-table", file: "bets-table.html", label: "Bets and activity", path: "components/bets-table.css"},
  {group: "Organisms", name: "hiw-dialog", file: "hiw-dialog.html", label: "How-it-works dialog", path: "components/hiw-dialog.css"},
  {group: "Organisms", name: "feed", file: "feed.html", label: "Feed layout", path: "components/feed.css"},
  {group: "Organisms", name: "betpanel", file: "betpanel.html", label: "Bet panel and dock", path: "components/betpanel.css"},
  {group: "Organisms", name: "profile", file: "profile.html", label: "Profile identity", path: "components/profile.css"},
  {group: "Organisms", name: "event-detail", file: "event-detail.html", label: "Event Detail layout", path: "components/event-detail.css"},
  {group: "Organisms", name: "tabs", file: "tabs.html", label: "Tabs", path: "components/tabs.css"},
  {group: "Organisms", name: "chart", file: "chart.html", label: "Price chart", path: "components/chart.css"},
  {group: "Patterns", name: "patterns", file: "patterns.html", label: "Patterns", path: "components/patterns/"},
  {group: "Patterns", name: "action-bar", file: "action-bar.html", label: "Action bar", path: "components/patterns/action-bar.css"},
  {group: "Patterns", name: "browse-shell", file: "browse-shell.html", label: "Browse shell", path: "components/patterns/browse-shell.css"},
  {group: "Patterns", name: "card-grid", file: "card-grid.html", label: "Card grid", path: "components/patterns/card-grid.css"},
  {group: "Patterns", name: "detail-shell", file: "detail-shell.html", label: "Detail shell", path: "components/patterns/detail-shell.css"},
  {group: "Patterns", name: "list-head", file: "list-head.html", label: "List head", path: "components/patterns/list-head.css"},
  {group: "Patterns", name: "position-list", file: "position-list.html", label: "Position list", path: "components/patterns/position-list.css"},
];

function pmRevealPanelRow() {
  var panel = document.querySelector('.sidebar');
  if (!panel) return;
  var row = panel.querySelector('.sidebar-page-link.active, .sidebar-sub-link.active') ||
            panel.querySelector('.sidebar-divider.active');
  if (!row) return;
  var r = row.getBoundingClientRect(), p = panel.getBoundingClientRect();
  if (r.top >= p.top && r.bottom <= p.bottom) return;   /* already shown: do not jump */
  panel.scrollTop += (r.top - p.top) - p.height / 3;
}

(function () {
  var host = document.querySelector('[data-kit-nav]');
  var current = document.body.getAttribute('data-kit-page') || '';
  if (host) {
    // The back arrow leaves the system for the thing the system is for: the
    // painted screens. Overview is not a component, so it is not in the
    // registry below; it is its own row above the first group, the way the
    // screens have an Overview row above their families.
    var h = ['<a href="../ui-visual/overview.html" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> Painted screens</a>',
             '<div class="sidebar-brand"><div class="sidebar-project-name">Design system</div></div>',
             // the switch acts on the page, not on the tree, so it sits above the
             // tree: the panel is 40 rows long and a control at its foot needs scrolling
             '<button type="button" class="theme-switch" aria-pressed="false"><span class="ts-swatches" aria-hidden="true"><span class="ts-sw ts-dark"></span><span class="ts-sw ts-light"></span></span><span class="ts-label">Vault</span></button>',
             '<nav class="sidebar-nav" aria-label="Design system">',
             '<a href="overview.html" class="sidebar-page-link' + (current === 'overview' ? ' active' : '') + '">Overview</a>'];
    // The group you are IN is marked as well as the page you are ON. The tree is
    // 45 rows in a panel that shows about 25, so on most pages the brass row is
    // below the fold and the panel opens saying nothing about where you are. The
    // screens tree has always marked the family; this is the same answer, and it
    // is what makes the two panels one vocabulary rather than two.
    var here = null;
    window.KIT_NAV.forEach(function (e) { if (e.name === current) here = e.group; });
    var group = null;
    window.KIT_NAV.forEach(function (e) {
      if (e.group !== group) {
        group = e.group;
        h.push('<div class="sidebar-divider' + (group === here ? ' active' : '') +
               '">' + group + '</div>');
      }
      h.push('<a href="' + e.file + '" class="sidebar-page-link' + (e.name === current ? ' active' : '') + '">' + e.label + '</a>');
      if (e.name === 'tokens') {
        h.push('<div class="sidebar-sub">');
        window.KIT_DOORS.forEach(function (d) {
          h.push('<a href="' + d.file + '" class="sidebar-sub-link">' + d.label + '</a>');
        });
        h.push('</div>');
      }
    });
    // The documents are the last group and not the first, because they are the
    // reasoning and the components are the thing. They are pages of the vitrine
    // like any other, so they are rows in the same tree: a link that leaves for
    // a .md file is a link out of the browser.
    var inDocs = window.KIT_DOCS.some(function (d) { return d.name === current; });
    h.push('<div class="sidebar-divider' + (inDocs ? ' active' : '') + '">The reasoning</div>');
    window.KIT_DOCS.forEach(function (d) {
      h.push('<a href="' + d.file + '" class="sidebar-page-link' + (d.name === current ? ' active' : '') + '">' + d.label + '</a>');
    });
    h.push('</nav>');
    // why.html is here and NOT a row in the tree above, and the difference is
    // what the tree is: a registry of things the system HAS. The guide is not a
    // component, a pattern or a document of the reasoning; it is the way in for
    // someone who has none of that vocabulary yet, so it sits where a person
    // looks when the tree has not helped. Gate 22 accepts a page off the tree
    // only when something still links it, and this is that link.
    // ON ONE LINE, and the comment may not name the class either. Gate 22 finds
    // this note by searching for its class name and reading to the end of the
    // LINE, so two things break it and both did: splitting the push across two
    // JS lines hides every link after the first, and writing the class name in a
    // comment ABOVE the push makes the search land on the comment, which has no
    // links at all. The second one turned shell.html and why.html unreachable in
    // the same run, from a comment that was explaining the first one.
    h.push('<div class="sidebar-note">New here? <a href="why.html">Why the system is like this</a><br>The kit itself: <a href="kit.html">kit.html</a>, <a href="shell.html">shell.html</a>, <a href="selftest.html">self test</a></div>');
    host.innerHTML = h.join('');
    // the tree exists only now, so the reveal happens here and not on load
    pmRevealPanelRow();
  }
  var cards = document.getElementById('kitCards');
  if (cards) {
    var g = null, out = [];
    window.KIT_NAV.forEach(function (e) {
      if (e.group !== g) { g = e.group; out.push('</div><h3 class="tk-subh">' + g + '</h3><div class="ck-cards">'); }
      var thumb = window.KIT_THUMBS && window.KIT_THUMBS[e.name];
      // A CARD WITH NO SPECIMEN IS A DOOR, and it has to say so. Two of the
      // sixty have none - the token page and the pattern index, which are pages
      // OF the system rather than components IN it - and in a grid row that
      // stretches to the tallest card they stood as a 224px plate with a label
      // at the bottom and nothing above it, which reads exactly like a
      // thumbnail that failed to load.
      out.push('<a class="ck-card' + (thumb ? '' : ' ck-card-door') + '" href="' + e.file + '">' +
               (thumb ? '<span class="ck-thumb"><iframe src="' + thumb.src +
                        '" width="' + thumb.w + '" height="' + thumb.h +
                        '" style="transform:scale(' + thumb.s + ')" loading="lazy" tabindex="-1" aria-hidden="true" title=""></iframe></span>' : '') +
               '<b>' + e.label + '</b><code>' + e.path + '</code></a>');
    });
    cards.innerHTML = (out.join('') + '</div>').replace(/^<\/div>/, '');
  }
  var doors = document.getElementById('kitDoors');
  if (doors) {
    doors.innerHTML = window.KIT_DOORS.map(function (d) {
      return '<a class="ck-card" href="' + d.file + '"><b>' + d.label + '</b><code>' + d.blurb + '</code></a>';
    }).join('');
  }
  var docs = document.getElementById('kitDocs');
  if (docs) {
    docs.innerHTML = window.KIT_DOCS.map(function (d) {
      return '<a class="ck-card" href="' + d.file + '"><b>' + d.label + '</b><code>' + d.blurb + '</code></a>';
    }).join('');
  }
  var sb = document.querySelector('[data-kit-nav]'), ov = document.getElementById('rmOverlay'), tg = document.getElementById('rmToggle');
  if (sb && ov && tg) {
    var o = function () { sb.classList.add('open'); ov.classList.add('open'); },
        c = function () { sb.classList.remove('open'); ov.classList.remove('open'); };
    tg.addEventListener('click', o); ov.addEventListener('click', c);
  }
})();
