/* ui-kit/_nav.js - the ONE registry of stand pages.

   It renders two things from the same list: the cards on overview.html and the
   kit-only side panel on every stand page. A component without a line here does
   not exist as far as the system is concerned. Own namespace (window.KIT_NAV) so
   it never collides with the course roadmap renderer in the repo root.
   Generated by _gen_component_pages.py. No em dash. */
window.KIT_DOORS = [{"label": "Colour", "file": "tokens.html#colour", "blurb": "Every graphite step and every brass, and the roles that read them."}, {"label": "Material", "file": "tokens.html#material", "blurb": "The two-stone plates, the grain, the bevels and the grooves."}, {"label": "Geometry", "file": "tokens.html#geometry", "blurb": "Spacing, radius, control sizes, the container and the gutter."}, {"label": "Type", "file": "tokens.html#type", "blurb": "Three families, the size ramp, weight and leading."}, {"label": "Motion", "file": "tokens.html#motion", "blurb": "Durations and easings, shown moving."}];
window.KIT_DOCS = [{"name": "doc-architecture", "file": "architecture.html", "label": "Architecture", "blurb": "How the system is put together, what each level may hold, and where a change goes."}, {"name": "doc-tokens-audit", "file": "tokens-audit.html", "label": "Tokens audit", "blurb": "The reading the system was built from: every value the painted product had, and what it meant."}, {"name": "doc-inventory", "file": "inventory.html", "label": "Inventory", "blurb": "Every component, its css file, its page and the screens it stands on."}, {"name": "doc-coverage", "file": "coverage.html", "label": "Coverage", "blurb": "Every class, and how many painted screens carry it. A zero is not a verdict."}];
window.KIT_NAV = [
  {group: "Foundations", name: "tokens", file: "tokens.html", label: "Tokens"},
  {group: "Foundations", name: "icons", file: "icons.html", label: "Icons"},
  {group: "Foundations", name: "base", file: "base.html", label: "Base and page frame"},
  {group: "Foundations", name: "course-chrome", file: "course-chrome.html", label: "Course chrome"},
  {group: "Atoms", name: "filters", file: "filters.html", label: "Sort and filters"},
  {group: "Atoms", name: "loadmore", file: "loadmore.html", label: "Load more"},
  {group: "Atoms", name: "oddsbar", file: "oddsbar.html", label: "Odds bar"},
  {group: "Atoms", name: "skeleton", file: "skeleton.html", label: "Skeletons"},
  {group: "Atoms", name: "button", file: "button.html", label: "Buttons"},
  {group: "Atoms", name: "input", file: "input.html", label: "Fields and amounts"},
  {group: "Molecules", name: "seo-plate", file: "seo-plate.html", label: "SEO plate"},
  {group: "Molecules", name: "trustbar", file: "trustbar.html", label: "Trust bar and cards"},
  {group: "Molecules", name: "market", file: "market.html", label: "AMM market panel"},
  {group: "Molecules", name: "account", file: "account.html", label: "Account bars"},
  {group: "Molecules", name: "related", file: "related.html", label: "Related events"},
  {group: "Molecules", name: "yesno", file: "yesno.html", label: "YES / NO buttons"},
  {group: "Molecules", name: "toast", file: "toast.html", label: "Toasts"},
  {group: "Molecules", name: "cookie-consent", file: "cookie-consent.html", label: "Cookie consent"},
  {group: "Organisms", name: "bottomnav", file: "bottomnav.html", label: "Bottom nav"},
  {group: "Organisms", name: "hiw-dialog", file: "hiw-dialog.html", label: "How-it-works dialog"},
  {group: "Organisms", name: "hero", file: "hero.html", label: "Featured hero"},
  {group: "Organisms", name: "comments", file: "comments.html", label: "Comments"},
  {group: "Organisms", name: "catnav", file: "catnav.html", label: "Category nav"},
  {group: "Organisms", name: "notice", file: "notice.html", label: "Notices and banners"},
  {group: "Organisms", name: "header", file: "header.html", label: "App header"},
  {group: "Organisms", name: "footer", file: "footer.html", label: "Footer"},
  {group: "Organisms", name: "options", file: "options.html", label: "Outcome rows"},
  {group: "Organisms", name: "state-block", file: "state-block.html", label: "State block"},
  {group: "Organisms", name: "card", file: "card.html", label: "Event card"},
  {group: "Organisms", name: "dialog", file: "dialog.html", label: "Shared dialog"},
  {group: "Organisms", name: "feed", file: "feed.html", label: "Feed layout"},
  {group: "Organisms", name: "betpanel", file: "betpanel.html", label: "Bet panel and dock"},
  {group: "Organisms", name: "profile", file: "profile.html", label: "Profile identity"},
  {group: "Organisms", name: "event-detail", file: "event-detail.html", label: "Event Detail layout"},
  {group: "Organisms", name: "position", file: "position.html", label: "Position rows"},
  {group: "Organisms", name: "bets-table", file: "bets-table.html", label: "Bets and activity"},
  {group: "Organisms", name: "tabs", file: "tabs.html", label: "Tabs"},
  {group: "Organisms", name: "chart", file: "chart.html", label: "Price chart"},
];

function pmRevealPanelRow() {
  var panel = document.querySelector('.sidebar');
  if (!panel) return;
  var row = panel.querySelector('.sidebar-page-link.active, .sidebar-sub-link.active') ||
            panel.querySelector('.sidebar-divider.active');
  if (!row) return;
  var r = row.getBoundingClientRect(), p = panel.getBoundingClientRect();
  if (r.top >= p.top && r.bottom <= p.bottom) return;   /* already shown: do not jump */
  panel.scrollTop += (r.top - p.top) - p.height / 3;
}

(function () {
  var host = document.querySelector('[data-kit-nav]');
  var current = document.body.getAttribute('data-kit-page') || '';
  if (host) {
    // The back arrow leaves the system for the thing the system is for: the
    // painted screens. Overview is not a component, so it is not in the
    // registry below; it is its own row above the first group, the way the
    // screens have an Overview row above their families.
    var h = ['<a href="../ui-visual/overview.html" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> Painted screens</a>',
             '<div class="sidebar-brand"><div class="sidebar-project-name">Design system</div></div>',
             // the switch acts on the page, not on the tree, so it sits above the
             // tree: the panel is 40 rows long and a control at its foot needs scrolling
             '<button type="button" class="theme-switch" aria-pressed="false"><span class="ts-swatches" aria-hidden="true"><span class="ts-sw ts-dark"></span><span class="ts-sw ts-light"></span></span><span class="ts-label">Vault</span></button>',
             '<nav class="sidebar-nav" aria-label="Design system">',
             '<a href="overview.html" class="sidebar-page-link' + (current === 'overview' ? ' active' : '') + '">Overview</a>'];
    // The group you are IN is marked as well as the page you are ON. The tree is
    // 45 rows in a panel that shows about 25, so on most pages the brass row is
    // below the fold and the panel opens saying nothing about where you are. The
    // screens tree has always marked the family; this is the same answer, and it
    // is what makes the two panels one vocabulary rather than two.
    var here = null;
    window.KIT_NAV.forEach(function (e) { if (e.name === current) here = e.group; });
    var group = null;
    window.KIT_NAV.forEach(function (e) {
      if (e.group !== group) {
        group = e.group;
        h.push('<div class="sidebar-divider' + (group === here ? ' active' : '') +
               '">' + group + '</div>');
      }
      h.push('<a href="' + e.file + '" class="sidebar-page-link' + (e.name === current ? ' active' : '') + '">' + e.label + '</a>');
      if (e.name === 'tokens') {
        h.push('<div class="sidebar-sub">');
        window.KIT_DOORS.forEach(function (d) {
          h.push('<a href="' + d.file + '" class="sidebar-sub-link">' + d.label + '</a>');
        });
        h.push('</div>');
      }
    });
    // The documents are the last group and not the first, because they are the
    // reasoning and the components are the thing. They are pages of the vitrine
    // like any other, so they are rows in the same tree: a link that leaves for
    // a .md file is a link out of the browser.
    var inDocs = window.KIT_DOCS.some(function (d) { return d.name === current; });
    h.push('<div class="sidebar-divider' + (inDocs ? ' active' : '') + '">The reasoning</div>');
    window.KIT_DOCS.forEach(function (d) {
      h.push('<a href="' + d.file + '" class="sidebar-page-link' + (d.name === current ? ' active' : '') + '">' + d.label + '</a>');
    });
    h.push('</nav>');
    h.push('<div class="sidebar-note">The kit itself: <a href="kit.html">kit.html</a>, <a href="shell.html">shell.html</a>, <a href="selftest.html">self test</a></div>');
    host.innerHTML = h.join('');
    // the tree exists only now, so the reveal happens here and not on load
    pmRevealPanelRow();
  }
  var cards = document.getElementById('kitCards');
  if (cards) {
    var g = null, out = [];
    window.KIT_NAV.forEach(function (e) {
      if (e.group !== g) { g = e.group; out.push('</div><h3 class="tk-subh">' + g + '</h3><div class="ck-cards">'); }
      var thumb = window.KIT_THUMBS && window.KIT_THUMBS[e.name];
      out.push('<a class="ck-card" href="' + e.file + '">' +
               (thumb ? '<span class="ck-thumb"><iframe src="specimens/' + thumb.id +
                        '.html" width="' + thumb.w + '" height="' + thumb.h +
                        '" style="transform:scale(' + thumb.s + ')" loading="lazy" tabindex="-1" aria-hidden="true" title=""></iframe></span>' : '') +
               '<b>' + e.label + '</b><code>' +
               (e.name === 'tokens' ? 'components/tokens.css'
                : e.name === 'icons' ? 'ui-kit/icons.html' : 'components/' + e.name + '.css') +
               '</code></a>');
    });
    cards.innerHTML = (out.join('') + '</div>').replace(/^<\/div>/, '');
  }
  var doors = document.getElementById('kitDoors');
  if (doors) {
    doors.innerHTML = window.KIT_DOORS.map(function (d) {
      return '<a class="ck-card" href="' + d.file + '"><b>' + d.label + '</b><code>' + d.blurb + '</code></a>';
    }).join('');
  }
  var docs = document.getElementById('kitDocs');
  if (docs) {
    docs.innerHTML = window.KIT_DOCS.map(function (d) {
      return '<a class="ck-card" href="' + d.file + '"><b>' + d.label + '</b><code>' + d.blurb + '</code></a>';
    }).join('');
  }
  var sb = document.querySelector('[data-kit-nav]'), ov = document.getElementById('rmOverlay'), tg = document.getElementById('rmToggle');
  if (sb && ov && tg) {
    var o = function () { sb.classList.add('open'); ov.classList.add('open'); },
        c = function () { sb.classList.remove('open'); ov.classList.remove('open'); };
    tg.addEventListener('click', o); ov.addEventListener('click', c);
  }
})();
