#!/usr/bin/env python3
"""
_resync_sidebar.py  -  Single source of truth for the LEFT sidebar on the
ui-visual (color) pages.

Unlike the root viz pages (which carry the 13-stage course roadmap, generated by
wireframes/_generators/resync_sidebar.py), the ui-visual pages follow the
WIREFRAME PRINCIPLE: the sidebar is a SCREEN TREE of the UI pages that actually
exist in the visual layer - not the whole course. On top it carries a single
"back to the course roadmap" affordance (-> research/research.html), so nothing
is lost.

Today only the Event Feed family is colored, so the tree lists those 9 pages
(logged-in + logged-out states), each a real clickable link, the current page
marked active. As more families are colored, add them to FAMILIES below and
re-run; the script is idempotent (like resync_sidebar.py / fixpack.py).

The block it rewrites is <aside class="sidebar" id="rmSidebar"> ... </aside>.
Styling lives in _theme.css (.sidebar-* + .sidebar-back / .sidebar-sub-head /
.sidebar-note). The rm-toggle / rm-overlay drawer + desktop dock are unchanged.

Usage:
    python3 _resync_sidebar.py          # rewrite all ui-visual pages
    python3 _resync_sidebar.py --check  # report which pages would change
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))       # ui-visual/
BACK_HREF = "../research/research.html"
BACK_LABEL = "Course roadmap"

# ---------------------------------------------------------------------------
# The colored screen families. Each family is a screen node with state rows,
# grouped by auth substate. Order here = order in the tree.
#   ("head", label)          -> a substate divider (Logged in / Logged out)
#   ("state", file, label)   -> one state page (real link)
# `built` families render as a live tree; `planned` ones render as a muted
# "Soon" line (they are genuinely not colored yet - honest, not dead links).
# ---------------------------------------------------------------------------
FAMILIES = [
    {
        "key": "event-feed",
        "label": "Event Feed",
        "built": True,
        "rows": [
            ("head", "Logged in"),
            ("state", "event-feed.html", "success"),
            ("state", "event-feed-empty.html", "empty"),
            ("state", "event-feed-error.html", "error"),
            ("state", "event-feed-loading.html", "loading"),
            ("state", "event-feed-push-permission-missing.html", "push-permission-missing"),
            ("head", "Logged out"),
            ("state", "event-feed-logged-out.html", "success"),
            ("state", "event-feed-logged-out-empty.html", "empty"),
            ("state", "event-feed-logged-out-error.html", "error"),
            ("state", "event-feed-logged-out-loading.html", "loading"),
        ],
    },
    # Colored next - listed as Soon so the stage scope is visible (no dead links):
    {"key": "event-detail", "label": "Event Detail", "built": False},
    {"key": "bet-confirm", "label": "Bet / Confirm", "built": False},
    {"key": "win-loss", "label": "Win / Loss", "built": False},
    {"key": "profile", "label": "Profile / Portfolio", "built": False},
]

# Every state file that exists -> its owning family (for the active check).
STATE_FILES = {
    row[1]
    for fam in FAMILIES if fam.get("built")
    for row in fam["rows"] if row[0] == "state"
}

ASIDE_RE = re.compile(r'<aside class="sidebar" id="rmSidebar">.*?</aside>', re.DOTALL)


def render_aside(active_file):
    L = [
        '<aside class="sidebar" id="rmSidebar">',
        '    <a href="{href}" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> {label}</a>'.format(
            href=BACK_HREF, label=BACK_LABEL),
        '    <div class="sidebar-brand"><div class="sidebar-project-name">UI + Visual - screens</div></div>',
        '    <div class="sidebar-nav">',
    ]
    for fam in FAMILIES:
        if not fam.get("built"):
            L.append('      <a class="sidebar-page-link planned">{}</a>'.format(fam["label"]))
            continue
        fam_active = active_file in {r[1] for r in fam["rows"] if r[0] == "state"}
        cls = "sidebar-page-link active" if fam_active else "sidebar-page-link"
        L.append('      <a class="{cls}">{label}</a>'.format(cls=cls, label=fam["label"]))
        L.append('      <div class="sidebar-sub">')
        for row in fam["rows"]:
            if row[0] == "head":
                L.append('        <div class="sidebar-sub-head">{}</div>'.format(row[1]))
            else:
                _, fpath, label = row
                acls = "sidebar-sub-link active" if fpath == active_file else "sidebar-sub-link"
                L.append('        <a href="{href}" class="{cls}">{label}</a>'.format(
                    href=fpath, cls=acls, label=label))
        L.append('      </div>')
    L.append('      <div class="sidebar-note">Other screen families join this tree as they are colored.</div>')
    L.append('    </div>')
    L.append('  </aside>')
    return "\n".join(L)


def process(fname, write=True):
    path = os.path.join(HERE, fname)
    with open(path, "r", encoding="utf-8") as fh:
        html = fh.read()
    m = ASIDE_RE.search(html)
    if not m:
        return "no-aside"
    new_aside = render_aside(fname)
    if new_aside == m.group(0):
        return "unchanged"
    if write:
        new_html = html[:m.start()] + new_aside + html[m.end():]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_html)
    return "updated"


def main():
    check = "--check" in sys.argv
    for fname in sorted(STATE_FILES):
        status = process(fname, write=not check)
        print("{:10s} {}".format(status, fname))


if __name__ == "__main__":
    main()
