#!/usr/bin/env python3
"""
_resync_sidebar.py  -  Single source of truth for the LEFT sidebar on the
ui-visual (color) pages.

Unlike the root viz pages (which carry the 13-stage course roadmap, generated by
wireframes/_generators/resync_sidebar.py), the ui-visual pages follow the
WIREFRAME PRINCIPLE: the sidebar is a SCREEN TREE of the UI pages that actually
exist in the visual layer - not the whole course. On top it carries a single
"back to the course roadmap" affordance (-> research/research.html), so nothing
is lost.

All 13 families are colored, so the tree lists all 76 state pages, each a real
clickable link, the current page marked active. Above them sits one row that
belongs to no family: Overview, the index of the painted screens, built by
_gen_overview.py. Add a page to FAMILIES below, re-run both scripts, and it
appears in the tree and on the index; the script is idempotent (like
resync_sidebar.py / fixpack.py).

The block it rewrites is <aside class="sidebar" id="rmSidebar"> ... </aside>.
Styling lives in _theme.css (.sidebar-* + .sidebar-back / .sidebar-sub-head /
.sidebar-note). The rm-toggle / rm-overlay drawer + desktop dock are unchanged.

Usage:
    python3 _resync_sidebar.py          # rewrite all ui-visual pages
    python3 _resync_sidebar.py --check  # report which pages would change
"""
import os
import re
import sys

from _theme_switch import BUTTON                        # the theme switch markup

HERE = os.path.dirname(os.path.abspath(__file__))       # ui-visual/
BACK_HREF = "../research/research.html"
BACK_LABEL = "Course roadmap"

# The index of the painted screens (built by _gen_overview.py). It sits above the
# families as its own row, because it is not a screen and belongs to no family:
# it is the front page every screen can get back to, and the place the design
# system's back arrow lands.
INDEX_FILE = "overview.html"
INDEX_LABEL = "Overview"

# ---------------------------------------------------------------------------
# The colored screen families. Each family is a screen node with state rows,
# grouped by auth substate. Order here = order in the tree.
#   ("head", label)          -> a substate divider (Logged in / Logged out)
#   ("state", file, label)   -> one state page (real link)
# `built` families render as a live tree; `planned` ones render as a muted
# "Soon" line (they are genuinely not colored yet - honest, not dead links).
# ---------------------------------------------------------------------------
FAMILIES = [
    {
        "key": "event-feed",
        "label": "Event Feed",
        "built": True,
        "rows": [
            ("head", "Logged in"),
            ("state", "event-feed.html", "success"),
            ("state", "event-feed-empty.html", "empty"),
            ("state", "event-feed-error.html", "error"),
            ("state", "event-feed-loading.html", "loading"),
            ("state", "event-feed-push-permission-missing.html", "push-permission-missing"),
            ("head", "Logged out"),
            ("state", "event-feed-logged-out.html", "success"),
            ("state", "event-feed-logged-out-empty.html", "empty"),
            ("state", "event-feed-logged-out-error.html", "error"),
            ("state", "event-feed-logged-out-loading.html", "loading"),
        ],
    },
    {
        # Per-category feed pages: the top nav is one page each, and each of them
        # carries the feed's own state set, because a listing that can be empty on
        # Trending can be empty on Politics. Bases by _gen_category.py, states by
        # _apply_theme.py; re-run those, then this script.
        #
        # Their own family and not four rows under Event Feed, which is where they
        # sat while only the bases existed: the grey tree has called this "Category
        # pages (second-level nav -> own page)" since Stage 05, and the two trees
        # naming one family differently is how the family went unnoticed.
        "key": "category",
        "label": "Category pages",
        "built": True,
        "rows": [row for cat, label in (("politics", "Politics"), ("crypto", "Crypto"),
                                        ("culture", "Culture"), ("general", "General"))
                 for row in (
                     ("head", label),
                     ("state", "event-feed-%s.html" % cat, "success"),
                     ("state", "event-feed-%s-empty.html" % cat, "empty"),
                     ("state", "event-feed-%s-error.html" % cat, "error"),
                     ("state", "event-feed-%s-loading.html" % cat, "loading"),
                     ("head", "%s, logged out" % label),
                     ("state", "event-feed-%s-logged-out.html" % cat, "success"),
                     ("state", "event-feed-%s-logged-out-empty.html" % cat, "empty"),
                     ("state", "event-feed-%s-logged-out-error.html" % cat, "error"),
                     ("state", "event-feed-%s-logged-out-loading.html" % cat, "loading"),
                 )],
    },
    {
        "key": "event-detail",
        "label": "Event Detail",
        "built": True,
        "rows": [
            ("head", "Logged in"),
            ("state", "event-detail.html", "binary"),
            ("state", "event-detail-multi.html", "multi"),
            ("state", "event-detail-resolved.html", "resolved"),
            ("state", "event-detail-loading.html", "loading"),
            ("state", "event-detail-error.html", "error"),
            ("head", "Placing a bet"),
            ("state", "event-detail-bet-reconcile.html", "price moved"),
            ("state", "event-detail-bet-insufficient.html", "low balance"),
            ("state", "event-detail-bet-processing.html", "processing"),
            ("state", "event-detail-bet-error.html", "on-chain error"),
            ("head", "Logged out"),
            ("state", "event-detail-logged-out.html", "binary"),
            ("state", "event-detail-logged-out-multi.html", "multi"),
            ("state", "event-detail-logged-out-loading.html", "loading"),
            ("state", "event-detail-logged-out-error.html", "error"),
        ],
    },
    {
        "key": "my-bets",
        "label": "My Bets",
        "built": True,
        "rows": [
            ("head", "Active"),
            ("state", "active-bets.html", "success"),
            ("state", "active-bets-empty-new.html", "empty (new)"),
            ("state", "active-bets-empty-resolved.html", "empty (resolved)"),
            ("state", "active-bets-loading.html", "loading"),
            ("state", "active-bets-error.html", "error"),
            ("head", "History"),
            ("state", "active-bets-history.html", "success"),
            ("state", "active-bets-history-empty.html", "empty"),
            ("state", "active-bets-history-loading.html", "loading"),
            ("state", "active-bets-history-error.html", "error"),
        ],
    },
    {
        "key": "win-loss",
        "label": "Win / Loss",
        "built": True,
        "rows": [
            ("head", "Win"),
            ("state", "win.html", "you were right"),
            ("state", "win-payout-pending.html", "payout pending"),
            ("state", "win-loading.html", "loading"),
            ("state", "win-error.html", "error"),
            ("head", "Loss"),
            ("state", "loss.html", "what happened"),
            ("state", "loss-loading.html", "loading"),
        ],
    },
    {
        "key": "favorites",
        "label": "Favorites",
        "built": True,
        "rows": [
            ("state", "favorites.html", "success"),
            ("state", "favorites-empty.html", "empty"),
            ("state", "favorites-loading.html", "loading"),
        ],
    },
    {
        "key": "notifications",
        "label": "Notifications",
        "built": True,
        "rows": [
            ("state", "notifications.html", "success"),
            ("state", "notifications-empty.html", "empty"),
            ("state", "notifications-error.html", "error"),
            ("state", "notifications-loading.html", "loading"),
            ("state", "notifications-push.html", "push permission"),
        ],
    },
    {
        "key": "wallet",
        "label": "Wallet",
        "built": True,
        "rows": [
            ("state", "wallet.html", "success"),
            ("state", "wallet-loading.html", "loading"),
            ("state", "wallet-error.html", "error"),
        ],
    },
    {
        "key": "my-profile",
        "label": "My Profile",
        "built": True,
        "rows": [
            ("state", "my-profile.html", "success"),
            ("state", "my-profile-loading.html", "loading"),
            ("state", "my-profile-error.html", "error"),
        ],
    },
    {
        "key": "public-profile",
        "label": "Public Profile",
        "built": True,
        "rows": [
            ("state", "public-profile.html", "success"),
            ("state", "public-profile-loading.html", "loading"),
            ("state", "public-profile-error.html", "error"),
            ("state", "public-profile-not-found.html", "not found"),
        ],
    },
    {
        "key": "how-it-works",
        "label": "How It Works",
        "built": True,
        "rows": [
            ("state", "how-it-works.html", "success"),
        ],
    },
    {
        "key": "sign-in",
        "label": "Sign In",
        "built": True,
        "rows": [
            ("state", "sign-in.html", "success"),
            ("state", "sign-in-loading.html", "loading"),
            ("state", "sign-in-error.html", "error"),
            ("state", "sign-in-provider-conflict.html", "provider conflict"),
        ],
    },
    {
        "key": "deposit",
        "label": "Add funds",
        "built": True,
        "rows": [
            ("state", "deposit.html", "success"),
            ("state", "deposit-loading.html", "loading"),
            ("state", "deposit-pending.html", "payment pending"),
            ("state", "deposit-error-card.html", "card declined"),
            ("state", "deposit-error-kyc.html", "KYC rejected"),
            ("state", "deposit-minimum-not-met.html", "minimum not met"),
            ("state", "deposit-widget-load-failure.html", "widget failed"),
        ],
    },
    {
        "key": "system",
        "label": "System",
        "built": True,
        "rows": [
            ("state", "404.html", "404 not found"),
            ("state", "500.html", "500 server error"),
            ("state", "maintenance.html", "maintenance"),
            ("state", "cookie-consent.html", "cookie consent"),
            ("state", "toasts.html", "toasts"),
        ],
    },
]

# Every state file that exists -> its owning family (for the active check).
STATE_FILES = {
    row[1]
    for fam in FAMILIES if fam.get("built")
    for row in fam["rows"] if row[0] == "state"
}

ASIDE_RE = re.compile(r'<aside class="sidebar" id="rmSidebar">.*?</aside>', re.DOTALL)


def render_aside(active_file):
    L = [
        '<aside class="sidebar" id="rmSidebar">',
        '    <a href="{href}" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> {label}</a>'.format(
            href=BACK_HREF, label=BACK_LABEL),
        '    <div class="sidebar-brand"><div class="sidebar-project-name">UI + Visual - screens</div></div>',
        # the switch acts on the screen, not on the tree, so it sits above the
        # tree: the tree is 77 rows long and a control at its foot needs scrolling
        '    ' + BUTTON,
        '    <div class="sidebar-nav">',
        '      <a href="{href}" class="sidebar-page-link{active}">{label}</a>'.format(
            href=INDEX_FILE, label=INDEX_LABEL,
            active=" active" if active_file == INDEX_FILE else ""),
    ]
    for fam in FAMILIES:
        if not fam.get("built"):
            L.append('      <a class="sidebar-page-link planned">{}</a>'.format(fam["label"]))
            continue
        fam_active = active_file in {r[1] for r in fam["rows"] if r[0] == "state"}
        cls = "sidebar-page-link active" if fam_active else "sidebar-page-link"
        L.append('      <a class="{cls}">{label}</a>'.format(cls=cls, label=fam["label"]))
        L.append('      <div class="sidebar-sub">')
        for row in fam["rows"]:
            if row[0] == "head":
                L.append('        <div class="sidebar-sub-head">{}</div>'.format(row[1]))
            else:
                _, fpath, label = row
                acls = "sidebar-sub-link active" if fpath == active_file else "sidebar-sub-link"
                L.append('        <a href="{href}" class="{cls}">{label}</a>'.format(
                    href=fpath, cls=acls, label=label))
        L.append('      </div>')
    # The note used to promise that more families would join the tree. They all
    # have, so it now points at the two things this tree cannot show: the same
    # pages laid out as chips, and the system they are painted with.
    L.append('      <div class="sidebar-note">All {n} families are colored. '
             'Overview lists them as chips; the system they are painted with is in '
             'ui-kit.</div>'.format(n=len([f for f in FAMILIES if f.get("built")])))
    L.append('    </div>')
    L.append('  </aside>')
    return "\n".join(L)


def process(fname, write=True):
    path = os.path.join(HERE, fname)
    with open(path, "r", encoding="utf-8") as fh:
        html = fh.read()
    m = ASIDE_RE.search(html)
    if not m:
        return "no-aside"
    new_aside = render_aside(fname)
    if new_aside == m.group(0):
        return "unchanged"
    if write:
        new_html = html[:m.start()] + new_aside + html[m.end():]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_html)
    return "updated"


def main():
    check = "--check" in sys.argv
    for fname in sorted(STATE_FILES | {INDEX_FILE}):
        status = process(fname, write=not check)
        print("{:10s} {}".format(status, fname))


if __name__ == "__main__":
    main()
