#!/usr/bin/env python3
"""
_resync_sidebar.py  -  Single source of truth for the LEFT sidebar on the
ui-visual (color) pages.

Unlike the root viz pages (which carry the 13-stage course roadmap, generated by
wireframes/_generators/resync_sidebar.py), the ui-visual pages follow the
WIREFRAME PRINCIPLE: the sidebar is a SCREEN TREE of the UI pages that actually
exist in the visual layer - not the whole course. On top it carries a single
"back to the course roadmap" affordance (-> research/research.html), so nothing
is lost.

Today only the Event Feed family is colored, so the tree lists those 9 pages
(logged-in + logged-out states), each a real clickable link, the current page
marked active. As more families are colored, add them to FAMILIES below and
re-run; the script is idempotent (like resync_sidebar.py / fixpack.py).

The block it rewrites is <aside class="sidebar" id="rmSidebar"> ... </aside>.
Styling lives in _theme.css (.sidebar-* + .sidebar-back / .sidebar-sub-head /
.sidebar-note). The rm-toggle / rm-overlay drawer + desktop dock are unchanged.

Usage:
    python3 _resync_sidebar.py          # rewrite all ui-visual pages
    python3 _resync_sidebar.py --check  # report which pages would change
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))       # ui-visual/
BACK_HREF = "../research/research.html"
BACK_LABEL = "Course roadmap"

# ---------------------------------------------------------------------------
# The colored screen families. Each family is a screen node with state rows,
# grouped by auth substate. Order here = order in the tree.
#   ("head", label)          -> a substate divider (Logged in / Logged out)
#   ("state", file, label)   -> one state page (real link)
# `built` families render as a live tree; `planned` ones render as a muted
# "Soon" line (they are genuinely not colored yet - honest, not dead links).
# ---------------------------------------------------------------------------
FAMILIES = [
    {
        "key": "event-feed",
        "label": "Event Feed",
        "built": True,
        "rows": [
            ("head", "Logged in"),
            ("state", "event-feed.html", "success"),
            ("state", "event-feed-empty.html", "empty"),
            ("state", "event-feed-error.html", "error"),
            ("state", "event-feed-loading.html", "loading"),
            ("state", "event-feed-push-permission-missing.html", "push-permission-missing"),
            ("head", "Logged out"),
            ("state", "event-feed-logged-out.html", "success"),
            ("state", "event-feed-logged-out-empty.html", "empty"),
            ("state", "event-feed-logged-out-error.html", "error"),
            ("state", "event-feed-logged-out-loading.html", "loading"),
            # Per-category feed pages (top nav = one page each; Trending is "success"
            # above). Generated by _gen_category.py; re-run that then this script.
            ("head", "Categories"),
            ("state", "event-feed-politics.html", "Politics"),
            ("state", "event-feed-crypto.html", "Crypto"),
            ("state", "event-feed-culture.html", "Culture"),
            ("state", "event-feed-general.html", "General"),
        ],
    },
    {
        "key": "event-detail",
        "label": "Event Detail",
        "built": True,
        "rows": [
            ("head", "Logged in"),
            ("state", "event-detail.html", "binary"),
            ("state", "event-detail-multi.html", "multi"),
            ("state", "event-detail-resolved.html", "resolved"),
            ("state", "event-detail-loading.html", "loading"),
            ("state", "event-detail-error.html", "error"),
            ("head", "Placing a bet"),
            ("state", "event-detail-bet-reconcile.html", "price moved"),
            ("state", "event-detail-bet-insufficient.html", "low balance"),
            ("state", "event-detail-bet-processing.html", "processing"),
            ("state", "event-detail-bet-error.html", "on-chain error"),
            ("head", "Logged out"),
            ("state", "event-detail-logged-out.html", "binary"),
            ("state", "event-detail-logged-out-multi.html", "multi"),
            ("state", "event-detail-logged-out-loading.html", "loading"),
            ("state", "event-detail-logged-out-error.html", "error"),
        ],
    },
    {
        "key": "my-bets",
        "label": "My Bets",
        "built": True,
        "rows": [
            ("head", "Active"),
            ("state", "active-bets.html", "success"),
            ("state", "active-bets-empty-new.html", "empty (new)"),
            ("state", "active-bets-empty-resolved.html", "empty (resolved)"),
            ("state", "active-bets-loading.html", "loading"),
            ("state", "active-bets-error.html", "error"),
            ("head", "History"),
            ("state", "active-bets-history.html", "success"),
            ("state", "active-bets-history-empty.html", "empty"),
            ("state", "active-bets-history-loading.html", "loading"),
            ("state", "active-bets-history-error.html", "error"),
        ],
    },
    {
        "key": "win-loss",
        "label": "Win / Loss",
        "built": True,
        "rows": [
            ("head", "Win"),
            ("state", "win.html", "you were right"),
            ("state", "win-payout-pending.html", "payout pending"),
            ("state", "win-loading.html", "loading"),
            ("state", "win-error.html", "error"),
            ("head", "Loss"),
            ("state", "loss.html", "what happened"),
            ("state", "loss-loading.html", "loading"),
        ],
    },
    {
        "key": "favorites",
        "label": "Favorites",
        "built": True,
        "rows": [
            ("state", "favorites.html", "success"),
            ("state", "favorites-empty.html", "empty"),
            ("state", "favorites-loading.html", "loading"),
        ],
    },
    {
        "key": "notifications",
        "label": "Notifications",
        "built": True,
        "rows": [
            ("state", "notifications.html", "success"),
            ("state", "notifications-empty.html", "empty"),
            ("state", "notifications-error.html", "error"),
            ("state", "notifications-loading.html", "loading"),
            ("state", "notifications-push.html", "push permission"),
        ],
    },
    {
        "key": "wallet",
        "label": "Wallet",
        "built": True,
        "rows": [
            ("state", "wallet.html", "success"),
            ("state", "wallet-loading.html", "loading"),
            ("state", "wallet-error.html", "error"),
        ],
    },
    {
        "key": "my-profile",
        "label": "My Profile",
        "built": True,
        "rows": [
            ("state", "my-profile.html", "success"),
            ("state", "my-profile-loading.html", "loading"),
            ("state", "my-profile-error.html", "error"),
        ],
    },
    {
        "key": "public-profile",
        "label": "Public Profile",
        "built": True,
        "rows": [
            ("state", "public-profile.html", "success"),
            ("state", "public-profile-loading.html", "loading"),
            ("state", "public-profile-error.html", "error"),
            ("state", "public-profile-not-found.html", "not found"),
        ],
    },
    {
        "key": "how-it-works",
        "label": "How It Works",
        "built": True,
        "rows": [
            ("state", "how-it-works.html", "success"),
        ],
    },
    {
        "key": "sign-in",
        "label": "Sign In",
        "built": True,
        "rows": [
            ("state", "sign-in.html", "success"),
            ("state", "sign-in-loading.html", "loading"),
            ("state", "sign-in-error.html", "error"),
            ("state", "sign-in-provider-conflict.html", "provider conflict"),
        ],
    },
    {
        "key": "deposit",
        "label": "Add funds",
        "built": True,
        "rows": [
            ("state", "deposit.html", "success"),
            ("state", "deposit-loading.html", "loading"),
            ("state", "deposit-pending.html", "payment pending"),
            ("state", "deposit-error-card.html", "card declined"),
            ("state", "deposit-error-kyc.html", "KYC rejected"),
            ("state", "deposit-minimum-not-met.html", "minimum not met"),
            ("state", "deposit-widget-load-failure.html", "widget failed"),
        ],
    },
    {
        "key": "system",
        "label": "System",
        "built": True,
        "rows": [
            ("state", "404.html", "404 not found"),
            ("state", "500.html", "500 server error"),
            ("state", "maintenance.html", "maintenance"),
            ("state", "cookie-consent.html", "cookie consent"),
            ("state", "toasts.html", "toasts"),
        ],
    },
]

# Every state file that exists -> its owning family (for the active check).
STATE_FILES = {
    row[1]
    for fam in FAMILIES if fam.get("built")
    for row in fam["rows"] if row[0] == "state"
}

ASIDE_RE = re.compile(r'<aside class="sidebar" id="rmSidebar">.*?</aside>', re.DOTALL)


def render_aside(active_file):
    L = [
        '<aside class="sidebar" id="rmSidebar">',
        '    <a href="{href}" class="sidebar-back"><span class="bk-arrow" aria-hidden="true">&larr;</span> {label}</a>'.format(
            href=BACK_HREF, label=BACK_LABEL),
        '    <div class="sidebar-brand"><div class="sidebar-project-name">UI + Visual - screens</div></div>',
        '    <div class="sidebar-nav">',
    ]
    for fam in FAMILIES:
        if not fam.get("built"):
            L.append('      <a class="sidebar-page-link planned">{}</a>'.format(fam["label"]))
            continue
        fam_active = active_file in {r[1] for r in fam["rows"] if r[0] == "state"}
        cls = "sidebar-page-link active" if fam_active else "sidebar-page-link"
        L.append('      <a class="{cls}">{label}</a>'.format(cls=cls, label=fam["label"]))
        L.append('      <div class="sidebar-sub">')
        for row in fam["rows"]:
            if row[0] == "head":
                L.append('        <div class="sidebar-sub-head">{}</div>'.format(row[1]))
            else:
                _, fpath, label = row
                acls = "sidebar-sub-link active" if fpath == active_file else "sidebar-sub-link"
                L.append('        <a href="{href}" class="{cls}">{label}</a>'.format(
                    href=fpath, cls=acls, label=label))
        L.append('      </div>')
    L.append('      <div class="sidebar-note">Other screen families join this tree as they are colored.</div>')
    L.append('    </div>')
    L.append('  </aside>')
    return "\n".join(L)


def process(fname, write=True):
    path = os.path.join(HERE, fname)
    with open(path, "r", encoding="utf-8") as fh:
        html = fh.read()
    m = ASIDE_RE.search(html)
    if not m:
        return "no-aside"
    new_aside = render_aside(fname)
    if new_aside == m.group(0):
        return "unchanged"
    if write:
        new_html = html[:m.start()] + new_aside + html[m.end():]
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_html)
    return "updated"


def main():
    check = "--check" in sys.argv
    for fname in sorted(STATE_FILES):
        status = process(fname, write=not check)
        print("{:10s} {}".format(status, fname))


if __name__ == "__main__":
    main()
